#!/bin/sh /etc/rc.common

START=90
STOP=90

USE_PROCD=1
PROG=/usr/sbin/http_proxy
NAME=http_proxy

start_service()
{
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$PROG" -d
	procd_close_instance
}

